name: Nightly ROI

on:
  schedule:
    - cron: "0 23 * * *"   # 23:00 UTC = 00:00 Africa/Lagos
  workflow_dispatch: {}     # lets you run it manually from the Actions tab

permissions: {}             # minimal permissions

jobs:
  nightly-roi:
    runs-on: ubuntu-latest
    steps:
      # (optional) wake the Render app first
      - name: Wake service
        run: |
          curl -sS -m 30 --retry 5 --retry-delay 5 --retry-connrefused \
            "${{ secrets.SERVICE_URL }}/health" || true

      - name: Wait for warmup
        run: sleep 15

      - name: Trigger ROI
        run: |
          set -euo pipefail
          curl -sS -m 120 --retry 5 --retry-delay 10 --retry-connrefused \
            -X POST \
            -H "x-api-key: ${{ secrets.ROI_ADMIN_KEY }}" \
            "${{ secrets.SERVICE_URL }}/admin/jobs/roi/run"

    # avoid overlapping runs if one is slow
    concurrency:
      group: nightly-roi
      cancel-in-progress: false
